[package]
name = "MaFurstRustApp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
firebase-rs = "1.0.3"
serde="*"
rand="*"
random_name_generator = "0.1.2"